#!/bin/bash
clear
########## COLOR ##########
ORANGE='\033[0;33m'
pp="\033[42m"
xz="\033[1;93m"
z="\033[96m"
NC="\033[0m"
g="\033[1;92m"
y='\033[1;33m' #yellow
clear

checking_sc
clear
echo -e "  ${y}┌──────────────────────────────────────────┐${NC}"
echo -e "  ${y}│${NC}                 MENU BOT            $NC"
echo -e "  ${y}└──────────────────────────────────────────┘${NC}"
echo -e "  ${y}┌──────────────────────────────────────────┐${NC}"
echo -e "  ${y}│${NC}${g} 1.${NC} \033[0;36m Menu BOT Panel ${NC}"
echo -e "  ${y}│${NC}${g} 2.${NC} \033[0;36m Menu BOT Notifikasi ${NC}"
echo -e "  ${y}│${NC}${g} 3.${NC} \033[0;36m Menu BOT Backup ${NC}"
echo -e "  ${y}│${NC}${g} x.${NC} \033[0;36m Exit Menu BOT ${NC}"
echo -e "  ${y}└──────────────────────────────────────────┘${NC}"
echo -e ""
read -p "   Select From Options [ 1 - 3 or x ] : " menu
case $menu in
1) clear ; checking_sc ; mbot-panel ;;
2) clear ; checking_sc ; bot ;;
3) clear ; checking_sc ; 
echo -e "Note: "
echo -e "Sebelum Menggunakan BOT Backup"
echo -e "Harap Setup Dulu ID & Bot Token Kamu !"
sleep 2
mbot-backup ;;
0) menu ;;
*) m-bot ;;
esac